package com.ourcookbook.cookbook.domain.model

/**
 * Ingredient Domain Model
 * Generated by AgentsOrchestrator - Backend Architect
 * 
 * Ingredient entity with amount, unit, and name as specified
 */

data class Ingredient(
    val id: Long = 0,
    val recipeId: Long,
    val amount: Double,
    val unit: MeasurementUnit,
    val name: String,
    val notes: String? = null,
    val position: Int = 0
) {
    // Display formatted amount with unit
    val displayAmount: String get() {
        return when (unit) {
            MeasurementUnit.UNIT -> amount.toInt().toString()
            else -> "$amount ${unit.abbreviation}"
        }
    }
    
    // Full display string
    val displayString: String get() {
        return "$displayAmount $name" + (notes?.let { " ($it)" } ?: "")
    }
    
    // Validation
    fun isValid(): Boolean {
        return amount > 0 && name.isNotBlank()
    }
    
    // Conversion utilities
    fun toMetric(): Ingredient? {
        if (unit.isMetric) return this
        
        val metricUnit = when (unit) {
            MeasurementUnit.TEASPOON -> MeasurementUnit.MILLILITER
            MeasurementUnit.TABLESPOON -> MeasurementUnit.MILLILITER
            MeasurementUnit.FLUID_OUNCE -> MeasurementUnit.MILLILITER
            MeasurementUnit.CUP -> MeasurementUnit.MILLILITER
            MeasurementUnit.PINT -> MeasurementUnit.MILLILITER
            MeasurementUnit.QUART -> MeasurementUnit.LITER
            MeasurementUnit.GALLON -> MeasurementUnit.LITER
            MeasurementUnit.OUNCE -> MeasurementUnit.GRAM
            MeasurementUnit.POUND -> MeasurementUnit.KILOGRAM
            else -> return null
        }
        
        val metricAmount = when (unit) {
            MeasurementUnit.TEASPOON -> amount * 4.92892
            MeasurementUnit.TABLESPOON -> amount * 14.7868
            MeasurementUnit.FLUID_OUNCE -> amount * 29.5735
            MeasurementUnit.CUP -> amount * 236.588
            MeasurementUnit.PINT -> amount * 473.176
            MeasurementUnit.QUART -> amount * 946.353
            MeasurementUnit.GALLON -> amount * 3785.41
            MeasurementUnit.OUNCE -> amount * 28.3495
            MeasurementUnit.POUND -> amount * 0.453592
            else -> amount
        }
        
        return this.copy(
            amount = metricAmount,
            unit = metricUnit
        )
    }
    
    fun toImperial(): Ingredient? {
        if (unit.isImperial) return this
        
        val imperialUnit = when (unit) {
            MeasurementUnit.MILLILITER -> MeasurementUnit.FLUID_OUNCE
            MeasurementUnit.LITER -> MeasurementUnit.FLUID_OUNCE
            MeasurementUnit.MILLIGRAM -> MeasurementUnit.OUNCE
            MeasurementUnit.GRAM -> MeasurementUnit.OUNCE
            MeasurementUnit.KILOGRAM -> MeasurementUnit.POUND
            else -> return null
        }
        
        val imperialAmount = when (unit) {
            MeasurementUnit.MILLILITER -> amount * 0.033814
            MeasurementUnit.LITER -> amount * 33.814
            MeasurementUnit.MILLIGRAM -> amount * 0.000035274
            MeasurementUnit.GRAM -> amount * 0.035274
            MeasurementUnit.KILOGRAM -> amount * 2.20462
            else -> amount
        }
        
        return this.copy(
            amount = imperialAmount,
            unit = imperialUnit
        )
    }
    
    companion object {
        fun create(
            recipeId: Long,
            amount: Double,
            unit: MeasurementUnit,
            name: String,
            notes: String? = null,
            position: Int = 0
        ): Ingredient {
            return Ingredient(
                recipeId = recipeId,
                amount = amount,
                unit = unit,
                name = name,
                notes = notes,
                position = position
            )
        }
    }
}
