package com.ourcookbook.cookbook.domain.model

/**
 * Measurement Unit Enum
 * Generated by AgentsOrchestrator - Backend Architect
 * 
 * Units for ingredient measurements with imperial and metric support
 */

enum class MeasurementUnit(
    val displayName: String,
    val abbreviation: String,
    val isImperial: Boolean,
    val isMetric: Boolean,
    val isVolume: Boolean,
    val isWeight: Boolean
) {
    // Volume - Imperial
    TEASPOON("Teaspoon", "tsp", isImperial = true, isVolume = true),
    TABLESPOON("Tablespoon", "tbsp", isImperial = true, isVolume = true),
    FLUID_OUNCE("Fluid Ounce", "fl oz", isImperial = true, isVolume = true),
    CUP("Cup", "cup", isImperial = true, isVolume = true),
    PINT("Pint", "pt", isImperial = true, isVolume = true),
    QUART("Quart", "qt", isImperial = true, isVolume = true),
    GALLON("Gallon", "gal", isImperial = true, isVolume = true),
    
    // Volume - Metric
    MILLILITER("Milliliter", "ml", isMetric = true, isVolume = true),
    LITER("Liter", "L", isMetric = true, isVolume = true),
    
    // Weight - Imperial
    OUNCE("Ounce", "oz", isImperial = true, isWeight = true),
    POUND("Pound", "lb", isImperial = true, isWeight = true),
    
    // Weight - Metric
    MILLIGRAM("Milligram", "mg", isMetric = true, isWeight = true),
    GRAM("Gram", "g", isMetric = true, isWeight = true),
    KILOGRAM("Kilogram", "kg", isMetric = true, isWeight = true),
    
    // Unit-less
    UNIT("Unit", "", isImperial = false, isMetric = false, isVolume = false, isWeight = false),
    PINCH("Pinch", "pinch", isImperial = true, isVolume = false, isWeight = false),
    DASH("Dash", "dash", isImperial = true, isVolume = false, isWeight = false);
    
    companion object {
        fun fromString(value: String): MeasurementUnit? {
            return entries.find { 
                it.name.equals(value, ignoreCase = true) || 
                it.abbreviation.equals(value, ignoreCase = true) ||
                it.displayName.equals(value, ignoreCase = true)
            }
        }
        
        fun getVolumeUnits(): List<MeasurementUnit> {
            return entries.filter { it.isVolume }
        }
        
        fun getWeightUnits(): List<MeasurementUnit> {
            return entries.filter { it.isWeight }
        }
        
        fun getImperialUnits(): List<MeasurementUnit> {
            return entries.filter { it.isImperial }
        }
        
        fun getMetricUnits(): List<MeasurementUnit> {
            return entries.filter { it.isMetric }
        }
    }
}
