package com.example.cookbook.domain.model

import java.time.Instant

/**
 * Recipe Domain Model
 * Generated by AgentsOrchestrator - Backend Architect
 * 
 * Core recipe entity with all required fields from specification
 */

data class Recipe(
    val id: Long = 0,
    val title: String,
    val description: String? = null,
    val instructions: String,
    val servings: Int? = null,
    val prepTime: Int? = null, // minutes
    val cookTime: Int? = null, // minutes
    val category: RecipeCategory,
    val rating: Float? = null,
    val favorite: Boolean = false,
    val version: Int = 1,
    val checksum: String, // SHA-256 hash
    val createdAt: Instant,
    val updatedAt: Instant,
    val cookbookId: Long? = null,
    val imagePath: String? = null,
    val source: String? = null, // For imported recipes
    val tags: List<String> = emptyList()
) {
    // Total time calculation
    val totalTime: Int? get() {
        return when {
            prepTime == null && cookTime == null -> null
            prepTime == null -> cookTime
            cookTime == null -> prepTime
            else -> prepTime!! + cookTime!!
        }
    }
    
    // Validation
    fun isValid(): Boolean {
        return title.isNotBlank() && 
               instructions.isNotBlank() &&
               checksum.isNotBlank()
    }
    
    // Copy with updated timestamp and version
    fun withUpdate(): Recipe {
        return this.copy(
            version = version + 1,
            updatedAt = Instant.now()
        )
    }
    
    companion object {
        fun create(
            title: String,
            instructions: String,
            category: RecipeCategory = RecipeCategory.MAIN,
            description: String? = null,
            servings: Int? = null,
            prepTime: Int? = null,
            cookTime: Int? = null
        ): Recipe {
            val now = Instant.now()
            // Temporary checksum - will be calculated properly in repository
            val tempChecksum = "temp-${now.toEpochMilli()}"
            return Recipe(
                title = title,
                description = description,
                instructions = instructions,
                servings = servings,
                prepTime = prepTime,
                cookTime = cookTime,
                category = category,
                checksum = tempChecksum,
                createdAt = now,
                updatedAt = now
            )
        }
    }
}

// Data class for Recipe with Ingredients (for detailed views)
data class RecipeWithIngredients(
    val recipe: Recipe,
    val ingredients: List<Ingredient> = emptyList()
)

// DTO for creating/updating recipes
data class RecipeDto(
    val title: String,
    val description: String? = null,
    val instructions: String,
    val servings: Int? = null,
    val prepTime: Int? = null,
    val cookTime: Int? = null,
    val category: RecipeCategory,
    val cookbookId: Long? = null,
    val imagePath: String? = null,
    val source: String? = null,
    val tags: List<String> = emptyList(),
    val ingredients: List<IngredientDto> = emptyList()
)

// DTO for ingredient creation/updating
data class IngredientDto(
    val amount: Double,
    val unit: MeasurementUnit,
    val name: String,
    val notes: String? = null,
    val position: Int = 0
)
