package com.example.cookbook.domain.model

/**
 * Recipe Category Enum
 * Generated by AgentsOrchestrator - Backend Architect
 * 
 * Categories for organizing recipes as specified in the requirements
 */

enum class RecipeCategory(val displayName: String, val iconRes: String? = null) {
    BREAKFAST("Breakfasts"),
    MAIN("Mains"),
    DESSERT("Desserts & Snacks"),
    SNACK("Snacks"),
    SIDE("Sides"),
    SAUCE("Sauces"),
    SPICE("Spices");
    
    companion object {
        fun fromString(value: String): RecipeCategory? {
            return entries.find { it.name.equals(value, ignoreCase = true) }
                ?: entries.find { it.displayName.equals(value, ignoreCase = true) }
        }
        
        fun getAllCategories(): List<RecipeCategory> {
            return entries.toList()
        }
    }
}
