package com.example.cookbook.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Cookbook Color Palette
 * Generated by AgentsOrchestrator - ArchitectUX
 * 
 * Food-inspired color scheme for the cookbook application
 */

// Primary Colors - Rich, warm tones inspired by cooking ingredients
val PrimaryRed = Color(0xFFB71C1C) // Deep tomato red
val PrimaryRedContainer = Color(0xFFFFDAD6)
val OnPrimary = Color(0xFFFFFFFF)
val OnPrimaryContainer = Color(0xFF410002)

// Primary Dark Theme
val PrimaryRedDark = Color(0xFFFFB4AB)
val PrimaryRedContainerDark = Color(0xFF8F0000)
val OnPrimaryDark = Color(0xFF5D1A1B)
val OnPrimaryContainerDark = Color(0xFFFFDAD6)

// Secondary Colors - Vibrant accent colors
val SecondaryOrange = Color(0xFFFF5722) // Vibrant orange
val SecondaryOrangeContainer = Color(0xFFFFDBCB)
val OnSecondary = Color(0xFFFFFFFF)
val OnSecondaryContainer = Color(0xFF3E1A00)

// Secondary Dark Theme
val SecondaryOrangeDark = Color(0xFFFFB59D)
val SecondaryOrangeContainerDark = Color(0xFF873D00)
val OnSecondaryDark = Color(0xFF4F2500)
val OnSecondaryContainerDark = Color(0xFFFFDBCB)

// Tertiary Colors - Fresh, natural tones
val TertiaryGreen = Color(0xFF4CAF50) // Fresh green
val TertiaryGreenContainer = Color(0xFFC8E6C9)
val OnTertiary = Color(0xFFFFFFFF)
val OnTertiaryContainer = Color(0xFF003800)

// Tertiary Dark Theme
val TertiaryGreenDark = Color(0xFF80E27E)
val TertiaryGreenContainerDark = Color(0xFF00521D)
val OnTertiaryDark = Color(0xFF003800)
val OnTertiaryContainerDark = Color(0xFFC8E6C9)

// Background Colors
val BackgroundLight = Color(0xFFFFFBFE) // Clean, light background
val OnBackgroundLight = Color(0xFF1C1B1F)

val BackgroundDark = Color(0xFF1C1B1F) // Dark background
val OnBackgroundDark = Color(0xFFE6E1E5)

// Surface Colors
val SurfaceLight = Color(0xFFFFFBFE)
val OnSurfaceLight = Color(0xFF1C1B1F)
val SurfaceVariantLight = Color(0xFFE7E0EC)
val OnSurfaceVariantLight = Color(0xFF49454F)

val SurfaceDark = Color(0xFF1C1B1F)
val OnSurfaceDark = Color(0xFFE6E1E5)
val SurfaceVariantDark = Color(0xFF49454F)
val OnSurfaceVariantDark = Color(0xFFCAC4D0)

// Error Colors
val ErrorRed = Color(0xFFB00020) // Error state red
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF410002)

val ErrorRedDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFB4AB)

// Outline Colors
val OutlineLight = Color(0xFF79747E)
val OutlineVariantLight = Color(0xFFCAC4D0)

val OutlineDark = Color(0xFF938F99)
val OutlineVariantDark = Color(0xFF49454F)

// Scrim Colors
val ScrimLight = Color(0xFF000000)
val ScrimDark = Color(0xFF000000)

// Inverse Colors
val InverseSurfaceLight = Color(0xFF313033)
val InverseOnSurfaceLight = Color(0xFFF5EFF4)
val InversePrimaryLight = Color(0xFFE6B7B8)

val InverseSurfaceDark = Color(0xFFE6E1E5)
val InverseOnSurfaceDark = Color(0xFF313033)
val InversePrimaryDark = Color(0xFF8F0000)

// Additional Cookbook-specific colors
val Cream = Color(0xFFFFF9C4) // Light cream for backgrounds
val WarmBrown = Color(0xFF795548) // Warm brown for accents
val GoldenYellow = Color(0xFFFFC107) // Golden yellow for highlights
val DeepPurple = Color(0xFF673AB7) // Deep purple for secondary accents

// Semantic colors for better readability
val SuccessGreen = Color(0xFF006400)
val WarningOrange = Color(0xFFFF8C00)
val InfoBlue = Color(0xFF0288D1)
