package com.example.cookbook.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Shapes
import androidx.compose.ui.unit.dp

/**
 * Cookbook Shape System
 * Generated by AgentsOrchestrator - ArchitectUX
 * 
 * Shape definitions for the cookbook application
 */

val CookbookShapes = Shapes(
    extraSmall = RoundedCornerShape(4.dp),
    small = RoundedCornerShape(8.dp),
    medium = RoundedCornerShape(12.dp),
    large = RoundedCornerShape(16.dp),
    extraLarge = RoundedCornerShape(24.dp)
)

// Additional shape definitions for specific components
val RecipeCardShape = RoundedCornerShape(12.dp)
val ButtonShape = RoundedCornerShape(8.dp)
val TextFieldShape = RoundedCornerShape(8.dp)
val ChipShape = RoundedCornerShape(16.dp) // Pill shape
val ImageShape = RoundedCornerShape(8.dp)
val DialogShape = RoundedCornerShape(24.dp)
val BottomSheetShape = RoundedCornerShape(16.dp, 16.dp, 0.dp, 0.dp)
val FloatingActionButtonShape = RoundedCornerShape(16.dp)

// Shape tokens for consistent usage
object ShapeTokens {
    val xxs = 4.dp
    val xs = 8.dp
    val sm = 12.dp
    val md = 16.dp
    val lg = 24.dp
    val xl = 32.dp
    val full = 50.dp // For circular shapes
}
