package com.example.cookbook.ui.theme

import androidx.compose.ui.unit.dp

/**
 * Cookbook Spacing System
 * Generated by AgentsOrchestrator - ArchitectUX
 * 
 * Consistent spacing tokens for the cookbook application
 */

object Spacing {
    // Extra extra small - Tight spacing
    val xxs = 4.dp
    
    // Extra small - Compact spacing
    val xs = 8.dp
    
    // Small - Standard small spacing
    val sm = 12.dp
    
    // Medium - Default spacing
    val md = 16.dp
    
    // Large - Generous spacing
    val lg = 24.dp
    
    // Extra large - Section spacing
    val xl = 32.dp
    
    // Extra extra large - Major section spacing
    val xxl = 48.dp
    
    // XXX Large - Page margins
    val xxxl = 64.dp
}

// Spacing extensions for easier usage
val Int.dp get() = this.dp

// Common spacing combinations
object Padding {
    val none = 0.dp
    val small = Spacing.sm
    val medium = Spacing.md
    val large = Spacing.lg
    
    // Screen padding
    val screenHorizontal = Spacing.md
    val screenVertical = Spacing.md
    val screen = Spacing.md
    
    // Card padding
    val card = Spacing.md
    val cardSmall = Spacing.sm
    
    // Button padding
    val buttonHorizontal = Spacing.lg
    val buttonVertical = Spacing.sm
    
    // Text field padding
    val textFieldHorizontal = Spacing.md
    val textFieldVertical = Spacing.sm
    
    // List item padding
    val listItemHorizontal = Spacing.md
    val listItemVertical = Spacing.sm
}

object Margin {
    val none = 0.dp
    val small = Spacing.sm
    val medium = Spacing.md
    val large = Spacing.lg
    
    // Between elements in a row/column
    val betweenSmall = Spacing.sm
    val betweenMedium = Spacing.md
    val betweenLarge = Spacing.lg
}
