package com.example.cookbook.ui.navigation

import androidx.compose.runtime.Composable
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.navigation.NavHostController
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.navArgument
import com.example.cookbook.ui.screens.cookbook.CookbookDetailScreen
import com.example.cookbook.ui.screens.cookbook.CookbookEditScreen
import com.example.cookbook.ui.screens.cookbook.CookbookListScreen
import com.example.cookbook.ui.screens.favorites.FavoritesScreen
import com.example.cookbook.ui.screens.home.HomeScreen
import com.example.cookbook.ui.screens.ocr.OcrScannerScreen
import com.example.cookbook.ui.screens.recipe.RecipeCreateScreen
import com.example.cookbook.ui.screens.recipe.RecipeDetailScreen
import com.example.cookbook.ui.screens.recipe.RecipeEditScreen
import com.example.cookbook.ui.screens.recipe.RecipeListScreen
import com.example.cookbook.ui.screens.search.SearchScreen
import com.example.cookbook.ui.screens.settings.SettingsScreen
import com.example.cookbook.ui.screens.sync.ConflictResolutionScreen
import com.example.cookbook.ui.screens.sync.SyncStatusScreen
import com.example.cookbook.ui.screens.auth.DriveAuthScreen

/**
 * Cookbook Navigation Graph
 * Generated by AgentsOrchestrator - Mobile App Builder
 * 
 * Main navigation host for the cookbook application
 */

@Composable
fun CookbookNavHost(
    navController: NavHostController = hiltViewModel<NavHostController>(),
    startDestination: String = Route.HOME
) {
    NavHost(
        navController = navController,
        startDestination = startDestination
    ) {
        // Home Screen
        composable(Route.HOME) {
            HomeScreen(
                onNavigateToRecipeList = { 
                    navController.navigate(Route.RECIPE_LIST) 
                },
                onNavigateToCookbookList = { 
                    navController.navigate(Route.COOKBOOK_LIST) 
                },
                onNavigateToSearch = { 
                    navController.navigate(Route.SEARCH) 
                },
                onNavigateToFavorites = { 
                    navController.navigate(Route.FAVORITES) 
                },
                onNavigateToSettings = { 
                    navController.navigate(Route.SETTINGS) 
                },
                onNavigateToSyncStatus = { 
                    navController.navigate(Route.SYNC_STATUS) 
                },
                onNavigateToOcrScanner = { 
                    navController.navigate(Route.OCR_SCANNER) 
                }
            )
        }
        
        // Recipe Screens
        composable(Route.RECIPE_LIST) {
            RecipeListScreen(
                onNavigateToRecipeDetail = { recipeId ->
                    navController.navigate(Route.recipeDetail(recipeId))
                },
                onNavigateToRecipeCreate = {
                    navController.navigate(Route.RECIPE_CREATE)
                },
                onNavigateBack = { navController.popBackStack() }
            )
        }
        
        composable(
            route = Route.RECIPE_DETAIL,
            arguments = listOf(navArgument(Route.ARG_RECIPE_ID) { 
                type = NavType.LongType 
            })
        ) { backStackEntry ->
            val recipeId = backStackEntry.arguments?.getLong(Route.ARG_RECIPE_ID) ?: return@composable
            RecipeDetailScreen(
                recipeId = recipeId,
                onNavigateToRecipeEdit = { 
                    navController.navigate(Route.recipeEdit(recipeId)) 
                },
                onNavigateBack = { navController.popBackStack() },
                onNavigateToCookbook = { cookbookId ->
                    navController.navigate(Route.cookbookDetail(cookbookId))
                }
            )
        }
        
        composable(Route.RECIPE_CREATE) {
            RecipeCreateScreen(
                onNavigateBack = { navController.popBackStack() },
                onRecipeCreated = { recipeId ->
                    navController.popBackStack()
                    navController.navigate(Route.recipeDetail(recipeId))
                }
            )
        }
        
        composable(
            route = Route.RECIPE_EDIT,
            arguments = listOf(navArgument(Route.ARG_RECIPE_ID) { 
                type = NavType.LongType 
            })
        ) { backStackEntry ->
            val recipeId = backStackEntry.arguments?.getLong(Route.ARG_RECIPE_ID) ?: return@composable
            RecipeEditScreen(
                recipeId = recipeId,
                onNavigateBack = { navController.popBackStack() },
                onRecipeUpdated = { 
                    navController.popBackStack() 
                }
            )
        }
        
        // Cookbook Screens
        composable(Route.COOKBOOK_LIST) {
            CookbookListScreen(
                onNavigateToCookbookDetail = { cookbookId ->
                    navController.navigate(Route.cookbookDetail(cookbookId))
                },
                onNavigateToCookbookCreate = {
                    navController.navigate(Route.COOKBOOK_CREATE)
                },
                onNavigateBack = { navController.popBackStack() }
            )
        }
        
        composable(
            route = Route.COOKBOOK_DETAIL,
            arguments = listOf(navArgument(Route.ARG_COOKBOOK_ID) { 
                type = NavType.LongType 
            })
        ) { backStackEntry ->
            val cookbookId = backStackEntry.arguments?.getLong(Route.ARG_COOKBOOK_ID) ?: return@composable
            CookbookDetailScreen(
                cookbookId = cookbookId,
                onNavigateToRecipeDetail = { recipeId ->
                    navController.navigate(Route.recipeDetail(recipeId))
                },
                onNavigateToCookbookEdit = { 
                    navController.navigate(Route.cookbookEdit(cookbookId)) 
                },
                onNavigateBack = { navController.popBackStack() }
            )
        }
        
        composable(Route.COOKBOOK_CREATE) {
            CookbookEditScreen(
                isCreating = true,
                onNavigateBack = { navController.popBackStack() },
                onCookbookSaved = { cookbookId ->
                    navController.popBackStack()
                    navController.navigate(Route.cookbookDetail(cookbookId))
                }
            )
        }
        
        composable(
            route = Route.COOKBOOK_EDIT,
            arguments = listOf(navArgument(Route.ARG_COOKBOOK_ID) { 
                type = NavType.LongType 
            })
        ) { backStackEntry ->
            val cookbookId = backStackEntry.arguments?.getLong(Route.ARG_COOKBOOK_ID) ?: return@composable
            CookbookEditScreen(
                cookbookId = cookbookId,
                isCreating = false,
                onNavigateBack = { navController.popBackStack() },
                onCookbookSaved = { 
                    navController.popBackStack() 
                }
            )
        }
        
        // Search Screen
        composable(Route.SEARCH) {
            SearchScreen(
                onNavigateToRecipeDetail = { recipeId ->
                    navController.navigate(Route.recipeDetail(recipeId))
                },
                onNavigateBack = { navController.popBackStack() }
            )
        }
        
        // OCR Scanner Screen
        composable(Route.OCR_SCANNER) {
            OcrScannerScreen(
                onNavigateBack = { navController.popBackStack() },
                onRecipeScanned = { recipeText ->
                    // Navigate to recipe create with pre-filled text
                    navController.popBackStack()
                    navController.navigate(Route.RECIPE_CREATE)
                }
            )
        }
        
        // Sync Screens
        composable(Route.SYNC_STATUS) {
            SyncStatusScreen(
                onNavigateToConflictResolution = { conflictId ->
                    navController.navigate(Route.conflictResolution(conflictId))
                },
                onNavigateBack = { navController.popBackStack() }
            )
        }
        
        composable(
            route = Route.CONFLICT_RESOLUTION,
            arguments = listOf(navArgument(Route.ARG_CONFLICT_ID) { 
                type = NavType.LongType 
            })
        ) { backStackEntry ->
            val conflictId = backStackEntry.arguments?.getLong(Route.ARG_CONFLICT_ID) ?: return@composable
            ConflictResolutionScreen(
                conflictId = conflictId,
                onNavigateBack = { navController.popBackStack() },
                onConflictResolved = { 
                    navController.popBackStack()
                }
            )
        }
        
        // Settings Screen
        composable(Route.SETTINGS) {
            SettingsScreen(
                onNavigateBack = { navController.popBackStack() },
                onNavigateToDriveAuth = { 
                    navController.navigate(Route.DRIVE_AUTH) 
                }
            )
        }
        
        // Google Drive Authentication
        composable(Route.DRIVE_AUTH) {
            DriveAuthScreen(
                onAuthSuccess = { 
                    navController.popBackStack() 
                },
                onAuthFailed = { 
                    navController.popBackStack() 
                }
            )
        }
        
        // Favorites Screen
        composable(Route.FAVORITES) {
            FavoritesScreen(
                onNavigateToRecipeDetail = { recipeId ->
                    navController.navigate(Route.recipeDetail(recipeId))
                },
                onNavigateBack = { navController.popBackStack() }
            )
        }
    }
}
