package com.ourcookbook.cookbook.data.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import com.ourcookbook.cookbook.domain.model.MeasurementUnit

/**
 * Ingredient Entity for Room Database
 * Generated by AgentsOrchestrator - Backend Architect
 * 
 * Room entity mapping for Ingredient domain model
 */

@Entity(
    tableName = "ingredients",
    indices = [
        Index(value = ["recipeId"]),
        Index(value = ["name"]),
        Index(value = ["position"])
    ],
    foreignKeys = [
        ForeignKey(
            entity = RecipeEntity::class,
            parentColumns = ["id"],
            childColumns = ["recipeId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class IngredientEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val recipeId: Long,
    val amount: Double,
    val unit: MeasurementUnit,
    val name: String,
    val notes: String? = null,
    val position: Int = 0
) {
    // Convert to domain model
    fun toDomain(): com.example.cookbook.domain.model.Ingredient {
        return com.example.cookbook.domain.model.Ingredient(
            id = id,
            recipeId = recipeId,
            amount = amount,
            unit = unit,
            name = name,
            notes = notes,
            position = position
        )
    }
    
    companion object {
        fun fromDomain(ingredient: com.example.cookbook.domain.model.Ingredient): IngredientEntity {
            return IngredientEntity(
                id = ingredient.id,
                recipeId = ingredient.recipeId,
                amount = ingredient.amount,
                unit = ingredient.unit,
                name = ingredient.name,
                notes = ingredient.notes,
                position = ingredient.position
            )
        }
    }
}
