package com.example.cookbook.data.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import com.example.cookbook.domain.model.RecipeCategory
import java.time.Instant

/**
 * Recipe Entity for Room Database
 * Generated by AgentsOrchestrator - Backend Architect
 * 
 * Room entity mapping for Recipe domain model
 */

@Entity(
    tableName = "recipes",
    indices = [
        Index(value = ["cookbookId"]),
        Index(value = ["category"]),
        Index(value = ["title"]),
        Index(value = ["favorite"]),
        Index(value = ["createdAt"]),
        Index(value = ["checksum"])
    ],
    foreignKeys = [
        ForeignKey(
            entity = CookbookEntity::class,
            parentColumns = ["id"],
            childColumns = ["cookbookId"],
            onDelete = ForeignKey.SET_NULL
        )
    ]
)
data class RecipeEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val description: String? = null,
    val instructions: String,
    val servings: Int? = null,
    val prepTime: Int? = null, // minutes
    val cookTime: Int? = null, // minutes
    val category: RecipeCategory,
    val rating: Float? = null,
    val favorite: Boolean = false,
    val version: Int = 1,
    val checksum: String, // SHA-256 hash
    val createdAt: Instant,
    val updatedAt: Instant,
    val cookbookId: Long? = null,
    val imagePath: String? = null,
    val source: String? = null
) {
    // Convert to domain model
    fun toDomain(): com.example.cookbook.domain.model.Recipe {
        return com.example.cookbook.domain.model.Recipe(
            id = id,
            title = title,
            description = description,
            instructions = instructions,
            servings = servings,
            prepTime = prepTime,
            cookTime = cookTime,
            category = category,
            rating = rating,
            favorite = favorite,
            version = version,
            checksum = checksum,
            createdAt = createdAt,
            updatedAt = updatedAt,
            cookbookId = cookbookId,
            imagePath = imagePath,
            source = source
        )
    }
    
    companion object {
        fun fromDomain(recipe: com.example.cookbook.domain.model.Recipe): RecipeEntity {
            return RecipeEntity(
                id = recipe.id,
                title = recipe.title,
                description = recipe.description,
                instructions = recipe.instructions,
                servings = recipe.servings,
                prepTime = recipe.prepTime,
                cookTime = recipe.cookTime,
                category = recipe.category,
                rating = recipe.rating,
                favorite = recipe.favorite,
                version = recipe.version,
                checksum = recipe.checksum,
                createdAt = recipe.createdAt,
                updatedAt = recipe.updatedAt,
                cookbookId = recipe.cookbookId,
                imagePath = recipe.imagePath,
                source = recipe.source
            )
        }
    }
}
