package com.ourcookbook.cookbook

import android.app.Application
import dagger.hilt.android.HiltAndroidApp

/**
 * Cookbook Application class
 * Generated by AgentsOrchestrator - Mobile App Builder
 * 
 * Main application class with Hilt dependency injection
 */
@HiltAndroidApp
class CookbookApplication : Application() {
    
    override fun onCreate() {
        super.onCreate()
        
        // Initialize application-level components
        // Database encryption will be handled by Room + SQLCipher
        // WorkManager will be initialized automatically
        
        // Log application startup
        // Timber.plant(Timber.DebugTree()) // Uncomment for debugging
    }
}
